version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  consumer:
    image: spring-boot-kafka-consumer-example
    container_name: spring-boot-kafka-consumer-example
    depends_on:
      - kafka
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - kafka
    links:
      - kafka:kafka

  producer:
    image: spring-boot-kafka-producer-example
    container_name: spring-boot-kafka-producer-example
    depends_on:
      - kafka
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - kafka
    links:
      - kafka:kafka